export const GET_ALBUMS ='GET_ALBUMS'
export const ADD_ALBUM ='ADD_ALBUM'
export const EDIT_ALBUM ='EDIT_ALBUM'
export const DELETE_ALBUM ='DELETE_ALBUM'
export const GET_ALBUM ='GET_ALBUM'

export const GET_USERS = 'GET_USERS'
export const LOAD_USER = 'LOAD_USER'
export const ADD_USER = 'ADD_USER'
export const DELETE_USER = 'DELETE_USER'
export const LOGIN_USER = 'LOGIN_USER'
export const LOGOUT_USER = 'LOGOUT_USER'